#!/bin/zsh

# Install Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"
brew update

# Install from Brewfile
brew tap homebrew/bundle
brew bundle

# Replace ~/.nanorc
#rm -rf $HOME/.nanorc
mv $HOME/.nanorc $HOME/.nanorc_dotfile_bkp
ln -s $PWD/.nanorc $HOME/.nanorc

# Enable syntax highlighting if Cellar is in non-standard location
echo 'include "'"$(brew --cellar nano)"'/*/share/nano/*.nanorc"' >> ~/.nanorc

# Clone powerlevel10k zsh theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Replace ~/.zshrc
#rm -rf $HOME/.zshrc
mv $HOME/.zshrc $HOME/.zshrc_dotfile_bkp
ln -s $PWD/.zshrc $HOME/.zshrc
